### ISSUE TITLE
Setup caching mechanism based on test generator being used. 

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli-jshint#15]
Since the generated linting files are actually the emitted output of the provided test generator, we need to ensure to entangle the tree generated by the `lintTree` hook with the currently in use test generator. 

This will require some coordination amongst ember-cli-qunit and ember-cli-mocha (as well as a similar update in ember-cli-eslint).

**Comment by rwjblue** [comment]
I believe that we should hang a `.baseDir()` and `.cacheKey()` off of the test generator function (which is setup in ember-cli-qunit and ember-cli-mocha), and then use that for the generated lint tree.

**Comment by Turbo87** [comment]
FWIW porting https://github.com/ember-cli/ember-cli-eslint/pull/176 to this addon should solve this issue too
